// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt7n_GOTjbnlI24fuSwilDwEMburvCqMo',
    appId: '1:899630335653:web:d01e9f034418d2cfba2f4c',
    messagingSenderId: '899630335653',
    projectId: 'inventorymanagementapp-dd4aa',
    authDomain: 'inventorymanagementapp-dd4aa.firebaseapp.com',
    storageBucket: 'inventorymanagementapp-dd4aa.firebasestorage.app',
    measurementId: 'G-WXX4B2Y8LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPWoEooAs-UmwI5ik957ray1DGh97ZTSQ',
    appId: '1:899630335653:android:acb6af0e82f6f4fdba2f4c',
    messagingSenderId: '899630335653',
    projectId: 'inventorymanagementapp-dd4aa',
    storageBucket: 'inventorymanagementapp-dd4aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv_FW5yJyDzr4hj93BTgmDggD9BJG5ljg',
    appId: '1:899630335653:ios:9c723d18dc09ad05ba2f4c',
    messagingSenderId: '899630335653',
    projectId: 'inventorymanagementapp-dd4aa',
    storageBucket: 'inventorymanagementapp-dd4aa.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv_FW5yJyDzr4hj93BTgmDggD9BJG5ljg',
    appId: '1:899630335653:ios:9c723d18dc09ad05ba2f4c',
    messagingSenderId: '899630335653',
    projectId: 'inventorymanagementapp-dd4aa',
    storageBucket: 'inventorymanagementapp-dd4aa.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt7n_GOTjbnlI24fuSwilDwEMburvCqMo',
    appId: '1:899630335653:web:bc824cb078b1dbb5ba2f4c',
    messagingSenderId: '899630335653',
    projectId: 'inventorymanagementapp-dd4aa',
    authDomain: 'inventorymanagementapp-dd4aa.firebaseapp.com',
    storageBucket: 'inventorymanagementapp-dd4aa.firebasestorage.app',
    measurementId: 'G-EF766SPKRK',
  );
}
